name: Metrics
on:
  # Se actualiza cada 24 horas autom치ticamente
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pesta침a Actions
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token por defecto de GitHub (no necesitas crear nada)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Configuraci칩n para que se parezca a tu tarjeta anterior
          user: javi-kl
          template: classic
          base: header, repositories
          config_timezone: Europe/Madrid
          
          # TUS COLORES (Migrados de tu URL anterior)
          config_style: |
            background-color: #0D1017;
            color: #E8EDF3;
            border-radius: 0px;
          
          # Nombre del archivo que se generar치
          filename: github-metrics.svg
