name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jakl
          
          # --- CONFIGURACIÓN MINIMALISTA ---
          # Desactivamos la cabecera gigante (header) y repositorios
          base: "" 
          
          # Activamos solo las stats clave (Estilo github-readme-stats)
          plugin_base: yes
          plugin_base_header: no
          plugin_base_indepth: yes 
          
          # Ajustamos el tamaño y estilo
          config_display: regular # Evita que sea "large"
          template: classic
          
          # TUS COLORES EXACTOS
          config_style: |
            background-color: #0D1017;
            color: #E8EDF3;
            border-radius: 0px;
          
          filename: github-metrics.svg

